Add crab3, accounting fixes, cpu count fix, corner cases fix.
amaltaro/scripts pull request #6
Opened 2017-03-09 10:10 UTC by juztas

@aperezca, as I said someday that I will take a look, see the list of fixes I added. This should solve some corner cases in accounting, it adds CRAB3 jobs, and also does correct accounting of Cpus for new WMAgent jobs, which now is set to ExprTree, not INT anymore.  Also small fixes which are known to be in CRAB or known in HTCondor as partially running (meaning it is in transfer state). So this should fix #5 #3 issues.
Regarding #4, isn't afs phasing out? who consumes this information? SST? As they already consume some information from cms-gwmsmon, it would be easy to add it in cms-gwmsmon and allow to access them through https. just a suggestion.

2017-03-09 10:52 UTC, aperezca commented
Hi Justas, thanks a lot for the fixes and changes! Now we need @amaltaro to merge them. 

About open issue you mentioned, #4, when we started reviewing this monitoring tool there was no sign of afs going away, at least as far as I know. And the point there still remains, namely where this thing should run and who should maintain it. Looking with broader perspective, I don't know what will become of this tool, to be honest, but that is for CMS computing as a whole to decide. The point with the issues I opened was (still is) to make it at usable again. 

Concerning its relation to cms-gwmsmon, the dashboard way of monitoring has some interesting features, like queries and custom plots which for the time being we can't find elsewhere. At the same time, we are using a CERN IT supported technology (well, for now…), so we just need to take care of injecting the data.

If we could run these scripts together with cms-gwmsmon and still feed the dashboard with this data that would be a great solution, I think. At least until CERN IT monitoring definitely moves from dashboard technology to something else (still, we'd need to keep the same functionality).

2017-03-09 12:27 UTC, juztas commented
Hi Antonio, my main suggestion was to run this script inside cms-gwmsmon and allow access to these files through https, and this would remove afs dependency.
I think it is not a push method to this dashboard, but something is pulling this info, no? So to pull from one or another url, it is a small change. 

Yes, sure, I am not arguing about movement and moving from one tool to another is fine if all use cases are covered, and in any case anyone from glideinwms team have access to cms-gwmsmon machine and always can change/modify any code or output.

2017-03-09 13:54 UTC, aperezca commented
Thanks for the additional changes, Justas.

"my main suggestion was to run this script inside cms-gwmsmon and allow access to these files through https, and this would remove afs dependency. I think it is not a push method to this dashboard, but something is pulling this info, no? So to pull from one or another url, it is a small change."

ok, let's try to find out whether it's push or pull and how easily it can be moved to another place, possibly Alan knows more about it, otherwise I could ask the CERN dashboard team.

2017-03-09 14:27 UTC, amaltaro commented
I still have to review these changes, but thanks anyways.

Dashboard consumes these information in a pull mode, so we just write a (or some) file(s) to afs and they read it from there and make the magic happen in dashboard. I'll check with Ed on what exactly is consumed.

2017-03-13 09:48 UTC, amaltaro requested changes
Thanks, Justas. I made a few comments and suggestions. Can reply/update them please?

2017-03-13 09:48 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                        workflow = job['WMAgent_SubTaskName'].split('/')[1]
you can replace it by `WMAgent_RequestName`

2017-03-13 09:48 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                    while '' in siteToExtract:
I don't really like it :) Why da hell crab is adding empty strings in the desired sites?
Anyways, I suggest to replace these 3 lines by a list comprehension like
`siteToExtract = [site for site in job['DESIRED_Sites'].replace(' ', '').split(",") if site]`

2017-03-13 09:48 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                        print 'No Sites... %s' % job
Instead of skipping this job, I'd rather "assign" it to a `NoSiteDefined` such that we could also spot such cases in the monitoring.

2017-03-13 09:48 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
Shouldn't we get this attr only for running jobs? So checking the job status before we get it?

2017-03-13 09:48 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                        if not 'T2_CH_CERN_T0' in siteToExtract:
It seems `T2_CH_CERN_T0` is not even in sitedb anymore. Should we just remove this double accounting "protection" code and blah blah?

2017-03-13 09:48 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                    if status == 2 and siteRunning:  # Running
this job status check is already done above, we should converge them into a single one.

2017-03-13 12:29 UTC, juztas commented on CondorMonitoring/JobCounter.py
> +                    while '' in siteToExtract:
You can always bug Marco and Emilis to fix it. And it is not solved for a long time already: https://github.com/dmwm/CRABServer/issues/4933

2017-03-13 12:30 UTC, juztas commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
no, see my first message in pull request

2017-03-13 12:30 UTC, juztas commented on CondorMonitoring/JobCounter.py
> +                        if not 'T2_CH_CERN_T0' in siteToExtract:
After discussion with Antonio, there is a bigger change, which means to ignore querying T0 pool.

2017-03-13 12:33 UTC, juztas commented on CondorMonitoring/JobCounter.py
> +                        workflow = job['WMAgent_SubTaskName'].split('/')[1]
1 vs 2 attributes? Better stick to one, which has and TaskName and SubTaskName. You can update it by yourself if you think differently

2017-03-13 13:07 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
I see no mention or explanation about job status and when or not to get the matched site name. Please elaborate.

2017-03-13 13:18 UTC, juztas commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
Also small fixes which are known to be in CRAB or known in HTCondor as partially running (meaning it is in transfer state.
From this elog https://cms-logbook.cern.ch/elog/GlideInWMS/5094
```
Sometimes there are zombie jobs, which do nothing. JobStatus is running, runtime is not increasing over 
time, they show as connected to a pilot from globalpool, but they do not have any MATCH_GLIDEIN_Entry_Name 
or any other attribute, except RemotePool. After some time, sometimes seconds, sometimes minutes, they 
start to have MATCH_GLIDEIN_Entry_Name and their runtime start to increase. From where this delay comes? 
All these kind of jobs are matched to T9_MIT_ZombieNoRunningSite
```
So you cannot assume on one attribute that job is really running there. Both has to be present, so jobStatus=2 and siteRunning is not empty. Sometimes this happens with crab, but as I already have fixed this in cms-gwmsmon for all (crab/prod), they are not easily noticeable.

2017-03-13 18:14 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
I see, thanks! Shouldn't we somehow still show these jobs in the monitoring then? Maybe we show them as pending? Or maybe we just show them as running at `NoSiteDefined`?

2017-03-14 09:45 UTC, amaltaro commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
@juztas @aperezca do you want to do something about these "transient" jobs? Or we just go with this code as it is now?

2017-03-14 09:51 UTC, juztas commented on CondorMonitoring/JobCounter.py
> +                    siteRunning = job.get(jobKeys[schedd_type]['sitename'], '')
I think it is not for that dashboard to monitor this. To really notice an issue here or long delays you would need a monitoring capable to do an order of 10s accuracy and map job by job. 
So for me jobs which are transferring sandboxes to a slot are still idle and during transfer anything can happen which prevents it from running (glexec, tcp failure, etc..), so I would not count them as running. And currently code is doing so. Only one thing is maybe to print in the log this

2017-03-17 14:23 UTC, amaltaro commented
Justas, can you just squash it please? :-) And then I'll give it a try still today.

2017-03-20 09:12 UTC, amaltaro commented
Thanks!

2017-03-20 09:12 UTC, merged

2017-03-20 09:22 UTC, amaltaro commented
These changes are live now and the next cycle (10:30 CERN time) should use the up-to-date code.

2017-03-20 09:47 UTC, amaltaro commented
@aperezca @juztas really that production is using ~140k cores at the moment and around 450k cpus idle?

The running cpus number kind of matches the cms-gwmsmon reported numbers. Pending cores is off by ~60k cpus.

BTW., the "Running jobs" & "Pending jobs" plots apparently have Cores/Slots information. And the lower plots have a much bigger number.

2017-03-20 12:47 UTC, aperezca commented
Hi Alan,

looking into this, http://submit-3.t2.ucsd.edu/CSstoragePath/aperez/HTML/global_pool_size_24h.html, I see about 175k used cores, about 120k for production, some 55k for analysis (T1s+T2s). We also have prod at T0, some 20k cores. About idle, there's some 600k cores overall. These numbers match the "jobs" metrics, but not the "slots" ones, which should be understood as cores, what is shown there is much higher and wrong. @juztas could you please check the proper numbers are being sent in the correct category?

2017-03-20 13:36 UTC, juztas commented
Boh, Where do you look for this? Comparing output which it produces with cms-gwmsmon or Antonio page, all seems logical and correct. Output logic was not changed, so there is still something what messes it up. 
I suspect one thing after looking at code, but I would need to know more details about dashboard and how it fetches, and which one key/value represents what.

2017-03-20 13:41 UTC, amaltaro commented
I've got some feedback from Eddie. I'm looking at this issue and will let you know later today.

2017-03-20 14:14 UTC, amaltaro commented
It doesn't seem like dashboard is doing anything funny with these metrics. They use 
http://cmst1.web.cern.ch/CMST1/CondorMonitoring/CondorMonitoring.json

as input for their script, which basically runs this code:
https://gitlab.cern.ch/exp_dashboard/cosmic/blob/master/dashboard.jobsmry-cms/lib/dashboard/collector/jobsmry/CMSCondorCollector.py#L51

The code looks good, and by running more or less the same code - but filtering only vocms0308 - I could reach the following job stats keyed by number of cores
```
{1: {'running': 16860, 'pending': 21721}, 3: {'running': 7541, 'pending': 27863}, 4: {'running': 7550, 'pending': 28761}, 5: {'running': 7388, 'pending': 25235}, 6: {'running': 7222, 'pending': 23376}, 7: {'running': 7029, 'pending': 22008}, 8: {'running': 7339, 'pending': 24838}, 9: {'running': 1813, 'pending': 8952}, 10: {'running': 1962, 'pending': 10046}}
```

which by eye, only 8, 9 and 10 cores would give us ~400k pending cores.

If there is a problem, it must be how we retrieve the number of cores from condor then... Justas, any insight?

2017-03-20 14:48 UTC, juztas commented
Minimized example:
```
                                    {
                                             "Pending": 735.5, 
                                             "Running": 175.0, 
                                             "Server": "vocms0311.cern.ch", 
                                             "Types": [
                                                      {
                                                               "NCores": [
                                                                        {
                                                                                 "Cores": 3, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 9.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 4, 
                                                                                 "Pending": 735.5, 
                                                                                 "Running": 16.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 5, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 1.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 6, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 5.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 8, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 3.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 9, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 1.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 10, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 4.0
                                                                        }
                                                               ], 
                                                               "Pending": 735.5, 
                                                               "Running": 39.0, 
                                                               "Type": "Processing"
                                                      }
                                             ]
                                    }, 
```
and dashboard code:
```
                for i in result['Sites']:
                    # self._logger.info('doing site %s ' % i)
                    for servers in i['Servers']:
                        if servers['Running'] != 0 or servers['Pending'] != 0:
                            for cores in servers['Types']:
                                if cores['NCores'] != []:
                                    for stats in cores['NCores']:
                                        jobStatus.append([update_time, i['Site'], servers['Server'], stats['Cores'], \
                                                           cores['Type'], int(cores['Running']), int(cores['Pending'])])
```

Which seems is done not correctly (I Think). Starting from this line:  `for stats in cores['NCores']:` it will append to the list these values:
```update_time, i['Site'], servers['Server'], stats['Cores'], cores['Type'], int(cores['Running']), int(cores['Pending'])```
while it should append:
```update_time, i['Site'], servers['Server'], stats['Cores'], cores['Type'], int(stats['Running']), int(stats['Pending'])```

Because what happens right now it takes overall numbers for all cores, but not specific numbers from stats dict. So for 3 cores it adds  735, for 4 - 735 and so on...


https://gitlab.cern.ch/exp_dashboard/cosmic/blob/master/dashboard.jobsmry-cms/lib/dashboard/collector/jobsmry/CMSCondorCollector.py#L59

2017-03-20 14:48 UTC, aperezca commented
This does not make sense, as this has to do with jdl magic in action: but the number of cores is not decided until after matching, so there is no possibility to have "3-cores pending". They have, for example:
RequestCPUs JobCpus OriginalCpus MinCores MaxCores => 3 3 4 3 10

So for jobs pending, we should count them as "original cpus"

2017-03-20 14:54 UTC, aperezca commented
Ok, so what Justas is pasting is actually right, (e.g. 9 core pending = 0) is the code afterwards which is making a mess of it

2017-03-20 14:55 UTC, amaltaro commented
Haaaa!! Well done Justas! That's it! I'm reporting this problem to Eddie and hopefully it will be fixed asap.

2017-03-20 14:56 UTC, juztas commented
@aperezca no need to look at other attributes, for matching you will look RequestCpus, which is evaluated already and will be OriginalCpus for idle jobs (as far as I can understand expressions), so:
``
$ condor_q -g -pool vocms032.cern.ch:9620 -af JobStatus RequestCpus | sort | uniq -c
 106188 1 1
 105050 1 4
 126786 2 1
    114 2 10
   1307 2 3
   9690 2 4
    311 2 5
    537 2 6
    121 2 7
   2452 2 8
    128 2 9
  39796 4 1
      1 4 3
    539 4 4
      8 4 8
  32132 5 1
    905 5 4
    824 5 8
```
Idle are only 1 or 4 core jobs.

2017-03-20 14:57 UTC, aperezca commented
Yes, I see, I was confused by what Alan posted and somehow thought we were looking at an incorrect job ad. Thanks!

2017-03-20 15:47 UTC, amaltaro commented
Script fixed as of 10min ago.

2017-03-20 17:06 UTC, aperezca commented
Looks much more reasonable now! Thanks!
Let's wait maybe 24h and see everything working fine, then we can contact some key people to let them know these plots can be used again (Stephan and site support at least)

2017-03-22 10:07 UTC, aperezca commented
Ok, I think it works with no problem now. Numbers agree with our other monitoring sources, so I think we can let site support team know that these plots are reliable again.

Thanks a lot @amaltaro and @juztas !